name: CI/CD workflow for Maven Build and Sonar Code scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17.0.13'

    # Step 3: Debug directory structure
    - name: Debug directory structure
      run: |
        echo "Listing all files:"
        ls -R

    # Step 4: Build with Maven
    - name: Build with Maven
      run: mvn clean install -f mvndemo/pom.xml

    # Step 5: SonarQube Scan
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v4.1.0
      with:
        projectBaseDir: mvndemo
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=my-Java-web-app
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
